# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

inhibit_all_warnings!

target 'ETEventTrackDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ETEventTrackDemo

  pod 'AFNetworking', '~> 3.2.1'
  pod 'SensorsAnalyticsSDK', :subspecs => ['IDFA', 'DISABLE_VTRACK', 'DISABLE_CALL_STACK', 'LOG']

end
